foreach(phase create render select scroll destroy)
    execute_process(COMMAND "${PROBE}" "${phase}" count RESULT_VARIABLE counted
        OUTPUT_VARIABLE attempts ERROR_VARIABLE problem TIMEOUT 10)
    if(NOT counted EQUAL 0 OR NOT attempts MATCHES "^[0-9]+[\r\n]*$")
        message(FATAL_ERROR "${phase} allocation inventory failed: ${counted} ${attempts} ${problem}")
    endif()
    string(STRIP "${attempts}" attempts)
    if(attempts GREATER 0)
        math(EXPR last "${attempts} - 1")
        foreach(failure RANGE 0 ${last})
            execute_process(COMMAND "${PROBE}" "${phase}" "${failure}" RESULT_VARIABLE recovered
                OUTPUT_VARIABLE output ERROR_VARIABLE problem TIMEOUT 10)
            if(NOT recovered EQUAL 0)
                message(FATAL_ERROR "${phase} allocation ${failure} did not recover: ${recovered} ${output} ${problem}")
            endif()
        endforeach()
    endif()
    message(STATUS "${phase}: ${attempts} allocation failure positions recovered")
endforeach()
