function(configure_identity directory enabled output)
    set(faults OFF)
    if(ARGC GREATER 3)
        set(faults "${ARGV3}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE}" -B "${ROOT}/${directory}" -G Ninja
        "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
        "-DNPS_RETAINED_UI=${enabled}" "-DNPS_RETAINED_FAULT_INJECTION=${faults}" -DNPS_QUALIFY_RETAINED_UI=OFF
        RESULT_VARIABLE configured OUTPUT_VARIABLE configure_output ERROR_VARIABLE configure_error)
    if(NOT configured EQUAL 0)
        message(FATAL_ERROR "Identity configuration failed: ${configure_output}\n${configure_error}")
    endif()
    file(READ "${ROOT}/${directory}/manifest/host/nps_manifest_config.h" manifest)
    string(REGEX MATCH "#define NPS_MANIFEST_ID [^\n]+" identity "${manifest}")
    if(NOT identity)
        message(FATAL_ERROR "Configured host identity is missing")
    endif()
    set(${output} "${identity}" PARENT_SCOPE)
endfunction()

configure_identity(first ON first_identity)
configure_identity(second ON second_identity)
if(NOT first_identity STREQUAL second_identity)
    message(FATAL_ERROR "Equal retained configurations differ across build directories")
endif()
configure_identity(second OFF disabled_identity)
if(first_identity STREQUAL disabled_identity)
    message(FATAL_ERROR "Retained and legacy builds have the same identity")
endif()
configure_identity(second ON restored_identity)
if(NOT first_identity STREQUAL restored_identity)
    message(FATAL_ERROR "Restoring the retained profile did not restore its identity")
endif()
configure_identity(second ON fault_identity ON)
if(first_identity STREQUAL fault_identity)
    message(FATAL_ERROR "Diagnostic failure controls share the release identity")
endif()
configure_identity(second ON restored_identity)
if(NOT first_identity STREQUAL restored_identity)
    message(FATAL_ERROR "Disabling failure controls did not restore the release identity")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE}" -B "${ROOT}/invalid-fault-profile" -G Ninja
    "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
    -DNPS_RETAINED_UI=OFF -DNPS_RETAINED_FAULT_INJECTION=ON
    RESULT_VARIABLE invalid_configured OUTPUT_VARIABLE invalid_output ERROR_VARIABLE invalid_error)
if(invalid_configured EQUAL 0 OR NOT invalid_error MATCHES "Retained failure injection requires NPS_RETAINED_UI")
    message(FATAL_ERROR "An invalid failure-injection profile was not specifically rejected: ${invalid_output}\n${invalid_error}")
endif()
message(STATUS "Retained identities distinguish release and diagnostic controls independently of build location")
